# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy React app via FTP Client

on:
  push:
    branches: [ main ]
        
  pull_request:
    branches: [ main ]
    
env:
   NODE_VERSION: '16.x' 
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Upload from public_html via FTP
      uses: CodeadGit/onlinekesif-client@main
      with:
        server: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        remote_dir: "/public_html/devop"
        local_dir: "static"
        delete: "false"
